[package]
name = "subproxy"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.52.2", features = ["full"] }
axum = { version = "0.8.9", features = ["macros"]}
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
serde_json = "1.0.150"
tower-http = { version = "0.7.0", features = ["cors", "fs"] }
tower = "0.5.3"
reqwest = "0.13.4"
base64 = "0.22.1"

[profile.release]
opt-level = "z"
strip = true
lto = true
panic = "abort"
